### PR TITLE
Add perturbations

### LINKED ISSUE #47: new dataset request: Add drug perturbation data from CMAP
It would be great if the following data set could be added to IMPROVE:

- Cmap drug perturbation data (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE101406 from https://www.sciencedirect.com/science/article/pii/S2405471218301091?via%3Dihub and https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5990023/)

Thanks in advance!

### PR DESCRIPTION
**Pull request by BelindaBGarana**
Resolves #47 
Still need IMPROVE FigShare link for perturbations.csv.gz in line 105 of build/cell_line/02b-cellLineLINCS.R

### CODE REVIEW

**Comment by jjacobson95** [comment]
A couple small updates before merging - it looks like these could be run sequentially, but instead of pulling the samples and drug files from local, it pulls from Figshare.  As Figshare will be constantly updating, these links become invalid. Can [02b-cellLineLINCS.R](https://github.com/PNNL-CompBio/coderdata/pull/64/commits/e176037f431bc0cbd61818870684d9ceb0223cc7#diff-a31b8bcce4dbf25d6683d89e4bcf82e2e1372f8c2f44f0101a6dfa6d3b4a07fe) be modified to change this. This will be helpful for the docker build / CI pipeline. 

There is a [drugs file](https://figshare.com/ndownloader/files/42357210) on Figshare that all of the other drugs files use - I'll create an issue for this because we need a static location for that.

**Comment by sgosline** [comment]
Is there a dockerfile to run this @BelindaBGarana ?

**Comment by BelindaBGarana** [comment]
No dockerfile in this PR because I thought I was asked not to make one yet @sgosline

**Comment by BelindaBGarana** [comment]
@jjacobson95 I just updated 02b-cellLineLINCS.R to use local file names instead of Figshare links. Please let me know if further changes are needed to fit into your larger pipeline. Thank you!

**Comment by sgosline** [comment]
I think it'd be easier to add a dockerfile so we know what packages and commands are required

**Pull request merged**
