### PR TITLE
Cell Line Datasets Separated, Improved Error Handling for all Build Scripts

### PR DESCRIPTION
**Pull request by jjacobson95**
***Ready to merge.***

Multiple Changes will be coming with this PR. 

**Summary:**
- Broad_sanger is **separated** into all of its component datasets. These include:
  - **CCLE**
  - **gCSI**
  - **GDSCv1**
  - **GDSCv2**
  - **CTRPv2**
  - **FIMM**
  - **PRISM**
 - This **separation** process includes several steps, that listed here to address #227:
   - [build/broad_sanger/05_separate_datasets.py](https://github.com/PNNL-CompBio/coderdata/compare/main...split_broad_sanger#diff-32c2624aa1d7c76eca281cf3ab5d6fe641a3f50d1333758b6a3f6dd76caadbc3) script - This performs the separation script.
   - [build/broad_sanger/build_misc.sh](https://github.com/PNNL-CompBio/coderdata/compare/main...split_broad_sanger#diff-3e9f5aa414a9af35a1c86736a3673b78431bc579c802ee09885b7bf689f5017c) - This calls the separation script in the broad_sanger_omics dockerfile.
   - [build/build_all.py](https://github.com/PNNL-CompBio/coderdata/compare/main...split_broad_sanger#diff-66c32588594860ef70dcd642a87b0f6faec23941f85a88100640aa8e57375dda) and [build/build_dataset.py](https://github.com/PNNL-CompBio/coderdata/compare/main...split_broad_sanger#diff-155e78f0e25f0d5f33fa7d58695075efd2d93ce7724208cbd9146e71e45ecd87) were modified to have a `process_misc` step. This is only called with broad_sanger but maybe other future datasets will require an additional final processing step as well.
   - **Validation and schema test** for each listed dataset and associated updated to  **[check_all_schemas.py](https://github.com/PNNL-CompBio/coderdata/compare/main...split_broad_sanger#diff-628760fd77e4f597f0114f9e3576ba134916f695ecd4cfa6efec97973a6a375f)**.

- **Error Handling** improved. Every bash script in the build process has been modified to appropriately pass an exit code to docker when its R or Python scripts fail. 
  - This will address the uncaught validation error in #233. 
  -  It also has some potential to affect #125, though we need a more direct method to handle this issue.

- **Schema Checking** revamped. All of the schema checking code has been moved into three files: schema/coderdata.yaml, schema/expected_files.yaml, scripts/check_schema.py.

- **Multiple Bug fixes and code updates to align to schema**. These include #233, #234, #236, #238, #239, #240.

### CODE REVIEW

**Comment by sgosline** [comment]
Is there a way to generalize the validation script so we only need one for all datasets? It feels like this is redundant and increases the burden on anyone wanting to add a dataset. Since all the files have the same file name structure ([datasetname]_[datatype]), can we just iterate through a directory and validate each one according to the file name?

**Comment by jjacobson95** [comment]
Yes, that is a more maintainable approach, I'll make that change!

Likely will use a decent amount of hard coded file names to ensure that all expected files are present (as is currently done) rather than simple pattern matching.

**Comment by sgosline** [comment]
I'd avoid hard-coded files. Perhaps use a config file that can be updated so the validation code itself remains the same.

**Comment by jjacobson95** [comment]
Good call, that sounds more elegant

**Comment by sgosline** [comment]
Please merge #242 before this.

**Comment by jjacobson95** [comment]
Merged. I've got one bug that I'm working on (The broad_sanger data split is working in the individual dataset script, but not in the build_all script) and then I'll rebuild all of the data.

**Comment by jjacobson95** [comment]
Just a note, I'm running into consistent memory issues when splitting the broad_sanger data in docker on AWS.  I'm reworking this script to reduce the memory usage.

**Comment by jjacobson95** [comment]
Resolves #227. This is the most notable update.
Resolves #233, #234,  #236 (with a schema fix to allow "Any"), #238, and #240. These are all bug and schema updates.
-We never made this an issue, but this moves all of the schema checking scripts into a single unified script that runs schema checking in parallel. Old schema code has been removed.

Closes #239. Not because this was resolved, but because it is a non-issue.

**Comment by jjacobson95** [comment]
Ready to merge!

**Comment by sgosline** [comment]
I reviewed this, and it looks solid!

**Pull request merged**
